language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
install:
- pip install pytest-cov coveralls flake8
- pip install pytest>=2.7.3 --upgrade
- pip install -e .
script:
- flake8
- import-order graphql
- py.test --cov=graphql tests
after_success:
- coveralls
