language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
cache: pip
install:
- pip install --cache-dir $HOME/.cache/pip pytest-cov pytest-mock coveralls flake8 isort==3.9.6 gevent==1.1b5 six>=1.10.0 pypromise>=0.3.0
- pip install --cache-dir $HOME/.cache/pip pytest>=2.7.3 --upgrade
- pip install -e .
script:
- flake8
- py.test --cov=graphql graphql tests
after_success:
- coveralls
matrix:
  include:
    - python: "3.5"
      script:
        - flake8
        - isort --check-only graphql/ -rc
        - py.test --cov=graphql graphql tests tests_py35
